/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;


import Controllers.ServerService;
import Jstartup.Jbuttonrenderizado;
import Jstartup.Usuario;
import Upload_System.Upload;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Tabla t = new Tabla();
    Tabla v = new Tabla();
    Usuario usuarioObj;
    public Home() {
        this(null);
    }

    public Home(Usuario user){
        initComponents();
        if(user!=null){
            this.usuarioObj = user;
        }else{
            this.usuarioObj = new Usuario("invitado", "guest@guest.com", "");
        }
        setColor(Home_btn); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Discover_btn,Create_btn}, new JPanel[]{ind_2,ind_3, ind_4});
        t.ver_tabla(timeline,"Timeline");
        v.ver_tabla(timeline1,"Discover");
        // jProgressBar1.setValue(50);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        // setSize(400,500);		
 
        setLocationRelativeTo(null);		
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Discover = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        timeline1 = new javax.swing.JTable();
        username = new javax.swing.JTextField();
        Username_label = new javax.swing.JLabel();
        pubblication_Date = new javax.swing.JTextField();
        Username_label1 = new javax.swing.JLabel();
        Search = new keeptoo.KButton();
        routine_diet_Type = new javax.swing.JComboBox<>();
        Search_Type_label = new javax.swing.JLabel();
        Choose_user_btn = new keeptoo.KButton();
        Choose_diet_btn = new keeptoo.KButton();
        publication_name = new javax.swing.JTextField();
        Publication_name_lbl = new javax.swing.JLabel();
        routine_diet_difficulty = new javax.swing.JComboBox<>();
        routine_time_per_week = new javax.swing.JComboBox<>();
        Choose_routine_btn = new keeptoo.KButton();
        side_pane = new javax.swing.JPanel();
        Home_btn = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Ranking_btn = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Discover_btn = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Create_btn = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        profile_photo = new javax.swing.JLabel();
        username_btn = new keeptoo.KButton();
        top_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        timeline = new javax.swing.JTable();
        Create = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pie_foto = new javax.swing.JTextArea();
        Subir = new javax.swing.JToggleButton();
        Ranking = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        user = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Discover.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel2.setName("Publication Date"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Discover");

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        timeline1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        timeline1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeline1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(timeline1);

        username.setBackground(new Color(0,0,0,0));
        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.setEnabled(false);
        username.setOpaque(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        Username_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username_label.setForeground(new java.awt.Color(255, 255, 255));
        Username_label.setText("username");

        pubblication_Date.setBackground(new Color(0,0,0,0));
        pubblication_Date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pubblication_Date.setForeground(new java.awt.Color(255, 255, 255));
        pubblication_Date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pubblication_Date.setCaretColor(new java.awt.Color(255, 255, 255));
        pubblication_Date.setEnabled(false);
        pubblication_Date.setOpaque(false);
        pubblication_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubblication_DateActionPerformed(evt);
            }
        });

        Username_label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username_label1.setForeground(new java.awt.Color(255, 255, 255));
        Username_label1.setText("Publication Date(dd/mm/YYYY)");

        Search.setBorder(null);
        Search.setText("Search");
        Search.setkBorderRadius(30);
        Search.setkEndColor(new java.awt.Color(255, 255, 255));
        Search.setkFillButton(false);
        Search.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Search.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Search.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Search.setkPressedColor(new java.awt.Color(51, 102, 255));
        Search.setkStartColor(new java.awt.Color(255, 255, 255));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        routine_diet_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Day", "Noon", "Breakfast" }));
        routine_diet_Type.setToolTipText("Filter");
        routine_diet_Type.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        routine_diet_Type.setEnabled(false);
        routine_diet_Type.setName(""); // NOI18N
        routine_diet_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routine_diet_TypeActionPerformed(evt);
            }
        });

        Search_Type_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search_Type_label.setForeground(new java.awt.Color(255, 255, 255));
        Search_Type_label.setText("Search Type:");

        Choose_user_btn.setBorder(null);
        Choose_user_btn.setText("User");
        Choose_user_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Choose_user_btn.setkBorderRadius(30);
        Choose_user_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Choose_user_btn.setkFillButton(false);
        Choose_user_btn.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Choose_user_btn.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Choose_user_btn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Choose_user_btn.setkPressedColor(new java.awt.Color(51, 102, 255));
        Choose_user_btn.setkStartColor(new java.awt.Color(255, 255, 255));
        Choose_user_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Choose_user_btnMousePressed(evt);
            }
        });
        Choose_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_user_btnActionPerformed(evt);
            }
        });

        Choose_diet_btn.setBorder(null);
        Choose_diet_btn.setText("diet");
        Choose_diet_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Choose_diet_btn.setkBorderRadius(30);
        Choose_diet_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Choose_diet_btn.setkFillButton(false);
        Choose_diet_btn.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Choose_diet_btn.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Choose_diet_btn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Choose_diet_btn.setkPressedColor(new java.awt.Color(51, 102, 255));
        Choose_diet_btn.setkStartColor(new java.awt.Color(255, 255, 255));
        Choose_diet_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Choose_diet_btnMousePressed(evt);
            }
        });
        Choose_diet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_diet_btnActionPerformed(evt);
            }
        });

        publication_name.setBackground(new Color(0,0,0,0));
        publication_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        publication_name.setForeground(new java.awt.Color(255, 255, 255));
        publication_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        publication_name.setCaretColor(new java.awt.Color(255, 255, 255));
        publication_name.setEnabled(false);
        publication_name.setOpaque(false);
        publication_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publication_nameActionPerformed(evt);
            }
        });

        Publication_name_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Publication_name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Publication_name_lbl.setText("Publication Name");

        routine_diet_difficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the difficulty", "Easy", "Medium", "Hard","Challenger" }));
        routine_diet_difficulty.setToolTipText("Filter");
        routine_diet_difficulty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        routine_diet_difficulty.setEnabled(false);
        routine_diet_difficulty.setName(""); // NOI18N
        routine_diet_difficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routine_diet_difficultyActionPerformed(evt);
            }
        });

        routine_time_per_week.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Days per Week", "2 days", "3 days", "4 days","5 days","6 days" }));
        routine_time_per_week.setToolTipText("Filter");
        routine_time_per_week.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        routine_time_per_week.setEnabled(false);
        routine_time_per_week.setName(""); // NOI18N
        routine_time_per_week.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routine_time_per_weekActionPerformed(evt);
            }
        });

        Choose_routine_btn.setBorder(null);
        Choose_routine_btn.setText("Routine");
        Choose_routine_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Choose_routine_btn.setkBorderRadius(30);
        Choose_routine_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Choose_routine_btn.setkFillButton(false);
        Choose_routine_btn.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Choose_routine_btn.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Choose_routine_btn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Choose_routine_btn.setkPressedColor(new java.awt.Color(51, 102, 255));
        Choose_routine_btn.setkStartColor(new java.awt.Color(255, 255, 255));
        Choose_routine_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Choose_routine_btnMousePressed(evt);
            }
        });
        Choose_routine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_routine_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_label1)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pubblication_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Publication_name_lbl)
                            .addComponent(publication_name, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(routine_diet_difficulty, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(routine_diet_Type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(routine_time_per_week, javax.swing.GroupLayout.Alignment.LEADING, 0, 230, Short.MAX_VALUE))
                            .addComponent(Username_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(Search_Type_label)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Choose_routine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Choose_user_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(Choose_diet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(135, 135, 135))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Choose_user_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(Search_Type_label)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(Choose_diet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Choose_routine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(Username_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Username_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pubblication_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Publication_name_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(publication_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(routine_diet_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(routine_diet_difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(routine_time_per_week, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DiscoverLayout = new javax.swing.GroupLayout(Discover);
        Discover.setLayout(DiscoverLayout);
        DiscoverLayout.setHorizontalGroup(
            DiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        DiscoverLayout.setVerticalGroup(
            DiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Discover, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        side_pane.setBackground(new java.awt.Color(0, 0, 0));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_btn.setBackground(new java.awt.Color(0, 0, 0));
        Home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Home_btnMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        javax.swing.GroupLayout Home_btnLayout = new javax.swing.GroupLayout(Home_btn);
        Home_btn.setLayout(Home_btnLayout);
        Home_btnLayout.setHorizontalGroup(
            Home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_btnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        Home_btnLayout.setVerticalGroup(
            Home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_btnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Home_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        Ranking_btn.setBackground(new java.awt.Color(23, 35, 51));
        Ranking_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ranking_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ranking_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ranking_btnMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ranking");

        javax.swing.GroupLayout Ranking_btnLayout = new javax.swing.GroupLayout(Ranking_btn);
        Ranking_btn.setLayout(Ranking_btnLayout);
        Ranking_btnLayout.setHorizontalGroup(
            Ranking_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking_btnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        Ranking_btnLayout.setVerticalGroup(
            Ranking_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking_btnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Ranking_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Ranking_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, -1));

        Discover_btn.setBackground(new java.awt.Color(0, 0, 0));
        Discover_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Discover_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Discover_btnMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Discover");

        javax.swing.GroupLayout Discover_btnLayout = new javax.swing.GroupLayout(Discover_btn);
        Discover_btn.setLayout(Discover_btnLayout);
        Discover_btnLayout.setHorizontalGroup(
            Discover_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Discover_btnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        Discover_btnLayout.setVerticalGroup(
            Discover_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Discover_btnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Discover_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Discover_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        Create_btn.setBackground(new java.awt.Color(23, 35, 51));
        Create_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Create_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Create_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Create_btnMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Create");

        javax.swing.GroupLayout Create_btnLayout = new javax.swing.GroupLayout(Create_btn);
        Create_btn.setLayout(Create_btnLayout);
        Create_btnLayout.setHorizontalGroup(
            Create_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        Create_btnLayout.setVerticalGroup(
            Create_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Create_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        profile_photo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profile_photo.setForeground(new java.awt.Color(255, 255, 255));
        profile_photo.setText("FOTO");
        side_pane.add(profile_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        username_btn.setBorder(null);
        username_btn.setText("@holahola");
        username_btn.setFont(new java.awt.Font("Yu Gothic Light", 0, 15)); // NOI18N
        username_btn.setkEndColor(new java.awt.Color(0, 0, 0));
        username_btn.setkFillButton(false);
        username_btn.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        username_btn.setkHoverForeGround(new java.awt.Color(51, 153, 255));
        username_btn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        username_btn.setkIndicatorThickness(1);
        username_btn.setkPressedColor(new java.awt.Color(0, 0, 0));
        username_btn.setkSelectedColor(new java.awt.Color(0, 0, 0));
        username_btn.setkStartColor(new java.awt.Color(0, 0, 0));
        username_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_btnActionPerformed(evt);
            }
        });
        side_pane.add(username_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 92, 28));
        username_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                username_btnMousePressed(evt);
            }
        });

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        top_panel.setBackground(new java.awt.Color(71, 120, 197));
        top_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                top_panelMouseDragged(evt);
            }
        });
        top_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                top_panelMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Share my gym");

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360)
                .addComponent(btn_exit)
                .addGap(27, 27, 27))
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        timeline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        timeline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timelineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(timeline);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        kGradientPanel3.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("UPLOAD PUBLICATION");

        jLabel6.setText("Publication Type");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rutina", "Dieta" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel12.setText("Comment:");

        pie_foto.setColumns(20);
        pie_foto.setRows(5);
        jScrollPane1.setViewportView(pie_foto);

        Subir.setText("Upload");
        Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Subir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel12))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(Subir)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RankingLayout = new javax.swing.GroupLayout(Ranking);
        Ranking.setLayout(RankingLayout);
        RankingLayout.setHorizontalGroup(
            RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        RankingLayout.setVerticalGroup(
            RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        jLabel2.setText("user");

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel2)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel2)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_btnMousePressed
        // TODO add your handling code here:
        setColor(Home_btn); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Discover_btn,Create_btn}, new JPanel[]{ind_2,ind_3, ind_4});
         home.setVisible(true);
         Create.setVisible(false);
         Discover.setVisible(false);
        Ranking.setVisible(false);
        user.setVisible(false);
        
       
    }//GEN-LAST:event_Home_btnMousePressed

    private void Discover_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discover_btnMousePressed
        // TODO add your handling code here:
         setColor(Discover_btn); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Home_btn,Create_btn}, new JPanel[]{ind_2,ind_1, ind_4});
         home.setVisible(false);
         Create.setVisible(false);
         Discover.setVisible(true);
        Ranking.setVisible(false);
        user.setVisible(false);
    }//GEN-LAST:event_Discover_btnMousePressed

    private void Create_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Create_btnMousePressed
        // TODO add your handling code here:
          setColor(Create_btn); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Discover_btn,Home_btn}, new JPanel[]{ind_2,ind_3, ind_1});
         home.setVisible(false);
         Create.setVisible(true);
         Discover.setVisible(false);
        Ranking.setVisible(false);
        user.setVisible(false);
        
    }//GEN-LAST:event_Create_btnMousePressed

    private void Ranking_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ranking_btnMouseReleased
        // TODO add your handling code here:
          setColor(Ranking_btn); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{Home_btn,Discover_btn,Create_btn}, new JPanel[]{ind_1,ind_3, ind_4});
         home.setVisible(false);
         Create.setVisible(false);
         Discover.setVisible(false);
        Ranking.setVisible(true);
        user.setVisible(false);
    }//GEN-LAST:event_Ranking_btnMouseReleased

    int xx,xy;
    private void top_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_panelMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_top_panelMousePressed

    private void top_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_panelMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_top_panelMouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void username_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_btnActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void timelineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timelineMouseClicked
        // TODO add your handling code here:
        
        int column = timeline.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/timeline.getRowHeight();
        
        if(row < timeline.getRowCount() && row >= 0 && column < timeline.getColumnCount() && column >= 0){
            Object value = timeline.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                if(boton.getName().equals("m")){
                    System.out.println("Click en el boton modificar");
                    //EVENTOS MODIFICAR
                }
                if(boton.getName().equals("e")){
                    JOptionPane.showConfirmDialog(null, "Desea eliminar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    System.out.println("Click en el boton eliminar");
                    //EVENTOS ELIMINAR
                }
                 if(boton.getName().equals("decripcion")){
                    JOptionPane.showConfirmDialog(null, "SOY DESCRIPCION", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    System.out.println("Click en el boton eliminar");
                    //EVENTOS ELIMINAR
                }
            }
            if(value instanceof JCheckBox){
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox)value;
                if(ch.isSelected()==true){
                    ch.setSelected(false);
                }
                if(ch.isSelected()==false){
                    ch.setSelected(true);
                }
                
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_timelineMouseClicked

    private void timeline1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeline1MouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        int column = timeline1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/timeline1.getRowHeight();
        
        if(row < timeline1.getRowCount() && row >= 0 && column < timeline1.getColumnCount() && column >= 0){
            Object value = timeline1.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                   
                if(boton.getName().equals("hola")){
                    System.out.println("holaaaa");
                    //EVENTOS MODIFICAR
                }else{
                    
                }
                if(boton.getName().equals("m")){
              
                    System.out.println("Click en el boton eliminar");
                    //EVENTOS ELIMINAR
                }
            
            }
            if(value instanceof JCheckBox){
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox)value;
                if(ch.isSelected()==true){
                    ch.setSelected(false);
                }
                if(ch.isSelected()==false){
                    ch.setSelected(true);
                }
                
            }
        }        // TODO 
        
    }//GEN-LAST:event_timeline1MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void pubblication_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubblication_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pubblication_DateActionPerformed

    private void SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMousePressed

    private void Choose_user_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choose_user_btnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choose_user_btnMousePressed

    private void Choose_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_user_btnActionPerformed
        // TODO add your handling code here:
        username.setEnabled(true);
        pubblication_Date.setEnabled(false);
        routine_diet_Type.setEnabled(false);
        publication_name.setEnabled(false);
        routine_diet_difficulty.setEnabled(false);
        routine_time_per_week.setEnabled(false);
        eleccion=1;
    }//GEN-LAST:event_Choose_user_btnActionPerformed

    private void Choose_diet_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choose_diet_btnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choose_diet_btnMousePressed

    private void Choose_diet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_diet_btnActionPerformed
        // TODO add your handling code here:
         username.setEnabled(false);
        pubblication_Date.setEnabled(true);
        routine_diet_Type.setEnabled(true);
        publication_name.setEnabled(true);
        routine_diet_difficulty.setEnabled(true);
        routine_time_per_week.setEnabled(false);
        eleccion=2;
    }//GEN-LAST:event_Choose_diet_btnActionPerformed

    private void routine_diet_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routine_diet_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routine_diet_TypeActionPerformed

    private void publication_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publication_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publication_nameActionPerformed

    private void routine_diet_difficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routine_diet_difficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routine_diet_difficultyActionPerformed

    private void routine_time_per_weekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routine_time_per_weekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routine_time_per_weekActionPerformed

    private void Choose_routine_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choose_routine_btnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choose_routine_btnMousePressed

    private void Choose_routine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_routine_btnActionPerformed
        // TODO add your handling code here:
        username.setEnabled(false);
        pubblication_Date.setEnabled(true);
        routine_diet_Type.setEnabled(false);
        publication_name.setEnabled(true);
        routine_diet_difficulty.setEnabled(true);
        routine_time_per_week.setEnabled(true);
        eleccion=3;
    }//GEN-LAST:event_Choose_routine_btnActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        //Controllers.Discover
    }//GEN-LAST:event_SearchActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirActionPerformed
        // TODO add your handling code here:
        Upload subir=new Upload(pie_foto.getText(),tipo.getSelectedIndex(), usuarioObj.getEmail(),usuarioObj.getPassword());
        
        subir.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_SubirActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        JSONObject obj = new JSONObject();
        obj.put("username", username.getText());
               
        String result = ServerService.sendPost("buscar.php", obj);
        if(!result.equals("ZERO_RESULTS")){
            JSONParser parser = new JSONParser();
            try {  
                JSONArray jArray = (JSONArray) parser.parse(result);
                for(int i=0;i<jArray.size();i++){
                    //JELem = jArray.get();
                    JSONArray jCurrent = (JSONArray) jArray.get(i);
                    
                    JOptionPane.showMessageDialog(null, jCurrent.toString(), "Información", JOptionPane.INFORMATION_MESSAGE);
                    //timeline.add
                }
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
             
    }//GEN-LAST:event_SearchMouseClicked
    private void lblMouseClicked(java.awt.event.MouseEvent evt){
        System.out.println("holaamigos");
    }
    private void bnt1MousePressed(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        Home h =new Home();
        h.setVisible(true);
        dispose();
        
        
    }
    private void username_btnMousePressed(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        home.setVisible(false);
        Create.setVisible(false);
        Discover.setVisible(false);
        Ranking.setVisible(false);
        user.setVisible(true);
        
        
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(0,0,0));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton Choose_diet_btn;
    private keeptoo.KButton Choose_routine_btn;
    private keeptoo.KButton Choose_user_btn;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Create_btn;
    private javax.swing.JPanel Discover;
    private javax.swing.JPanel Discover_btn;
    private javax.swing.JPanel Home_btn;
    private javax.swing.JLabel Publication_name_lbl;
    private javax.swing.JPanel Ranking;
    private javax.swing.JPanel Ranking_btn;
    private keeptoo.KButton Search;
    private javax.swing.JLabel Search_Type_label;
    private javax.swing.JToggleButton Subir;
    private javax.swing.JLabel Username_label;
    private javax.swing.JLabel Username_label1;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel home;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JTextArea pie_foto;
    private javax.swing.JLabel profile_photo;
    private javax.swing.JTextField pubblication_Date;
    private javax.swing.JTextField publication_name;
    private javax.swing.JComboBox<String> routine_diet_Type;
    private javax.swing.JComboBox<String> routine_diet_difficulty;
    private javax.swing.JComboBox<String> routine_time_per_week;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTable timeline;
    private javax.swing.JTable timeline1;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JPanel top_panel;
    private javax.swing.JPanel user;
    private javax.swing.JTextField username;
    private keeptoo.KButton username_btn;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel foto_c;
    private int eleccion;
    
}
