/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;


import Controllers.ServerService;
import Jstartup.Jbuttonrenderizado;
import Jstartup.Usuario;
import Publications.imagen;
import Upload_System.Upload;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.*; 
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
    
    private java.util.List<imagen> imagenes_busqueda= new LinkedList<imagen>();
    private java.util.List<imagen> imagenes_timeline= new LinkedList<imagen>();
    private  String ranking_array;
    private String[][] ranking_matriz=new String[10][2];
    /**
     * Creates new form Home
     */
    Tabla t = new Tabla();
    Tabla v ;
    tabla_ranking ranking_table;
    Usuario usuarioObj;
    public Home()  {
        this(null);
    }

    public Home(Usuario user){
        initComponents();
        if(user!=null){
            this.usuarioObj = user;
        }else{
            this.usuarioObj = new Usuario("invitado", "guest@guest.com", "");
        }
        setColor(Home_btn); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Discover_btn,Create_btn}, new JPanel[]{ind_2,ind_3, ind_4});
   
       
      
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        // setSize(400,500);		
        
         JSONObject obj = new JSONObject();
        obj.put("username", username.getText());
               
        String result = ServerService.sendPost("home.php", obj);
        if(!result.equals("ZERO_RESULTS")){
            JSONParser parser = new JSONParser();
            try {  
                JSONArray jArray = (JSONArray) parser.parse(result);
            
                imagenes_timeline=t.ver_tabla(timeline,"Timeline",jArray);
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //OBTENEMOS E INSERTAMOS RANKING EN LA TABLA
        
        
        ranking_array = ServerService.sendPost("ranking.php", obj);
         JSONParser parser = new JSONParser();
            try {  
                JSONArray jArray = (JSONArray) parser.parse(ranking_array);
                Object array_array[]=jArray.toArray();
                
                for(int w=0;w<array_array.length;w++){
                    JSONArray c =(JSONArray) array_array[w];
                    ranking_matriz[w][0]=(String) c.get(0);
                   ranking_matriz[w][1]=(String) c.get(1);
                }
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            ranking_table=new tabla_ranking();
            ranking_table.ver_tabla(ranking, ranking_matriz);
              for(int i=0;i<10;i++){
                for(int j=0;j<2;j++){
                 System.out.println(ranking_matriz[i][j]);
                }
              }
            
        
        
   
        
       username_btn.setText("@"+usuarioObj.getUser());
        setLocationRelativeTo(null);		
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        timeline = new javax.swing.JTable();
        Discover = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        busqueda_table = new javax.swing.JTable();
        username = new javax.swing.JTextField();
        Username_label = new javax.swing.JLabel();
        Search = new keeptoo.KButton();
        Search_Type_label = new javax.swing.JLabel();
        Choose_user_btn = new keeptoo.KButton();
        Choose_diet_btn = new keeptoo.KButton();
        Choose_routine_btn = new keeptoo.KButton();
        side_pane = new javax.swing.JPanel();
        Home_btn = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Ranking_btn = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Discover_btn = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Create_btn = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        username_btn = new keeptoo.KButton();
        top_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        Create = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pie_foto = new javax.swing.JTextArea();
        Subir = new javax.swing.JToggleButton();
        Ranking = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JTable();
        user = new javax.swing.JPanel();
        User_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        user_user = new javax.swing.JLabel();
        name_user = new javax.swing.JLabel();
        surname_user = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        biografia = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        modify_name = new javax.swing.JTextField();
        modify_surname = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        modify_bio = new javax.swing.JTextArea();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        timeline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timelineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(timeline);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        Discover.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel2.setName("Publication Date"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Discover");

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        busqueda_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        busqueda_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busqueda_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(busqueda_table);

        username.setBackground(new Color(0,0,0,0));
        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.setEnabled(false);
        username.setOpaque(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        Username_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username_label.setForeground(new java.awt.Color(255, 255, 255));
        Username_label.setText("username");

        Search.setBorder(null);
        Search.setText("Search");
        Search.setkBorderRadius(30);
        Search.setkEndColor(new java.awt.Color(255, 255, 255));
        Search.setkFillButton(false);
        Search.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Search.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Search.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Search.setkPressedColor(new java.awt.Color(51, 102, 255));
        Search.setkStartColor(new java.awt.Color(255, 255, 255));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Search_Type_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search_Type_label.setForeground(new java.awt.Color(255, 255, 255));
        Search_Type_label.setText("Search Type:");

        Choose_user_btn.setBorder(null);
        Choose_user_btn.setText("User");
        Choose_user_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Choose_user_btn.setkBorderRadius(30);
        Choose_user_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Choose_user_btn.setkFillButton(false);
        Choose_user_btn.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Choose_user_btn.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Choose_user_btn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Choose_user_btn.setkPressedColor(new java.awt.Color(51, 102, 255));
        Choose_user_btn.setkStartColor(new java.awt.Color(255, 255, 255));
        Choose_user_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Choose_user_btnMousePressed(evt);
            }
        });
        Choose_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_user_btnActionPerformed(evt);
            }
        });

        Choose_diet_btn.setBorder(null);
        Choose_diet_btn.setText("diet");
        Choose_diet_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Choose_diet_btn.setkBorderRadius(30);
        Choose_diet_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Choose_diet_btn.setkFillButton(false);
        Choose_diet_btn.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Choose_diet_btn.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Choose_diet_btn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Choose_diet_btn.setkPressedColor(new java.awt.Color(51, 102, 255));
        Choose_diet_btn.setkStartColor(new java.awt.Color(255, 255, 255));
        Choose_diet_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Choose_diet_btnMousePressed(evt);
            }
        });
        Choose_diet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_diet_btnActionPerformed(evt);
            }
        });

        Choose_routine_btn.setBorder(null);
        Choose_routine_btn.setText("Routine");
        Choose_routine_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Choose_routine_btn.setkBorderRadius(30);
        Choose_routine_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Choose_routine_btn.setkFillButton(false);
        Choose_routine_btn.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        Choose_routine_btn.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        Choose_routine_btn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        Choose_routine_btn.setkPressedColor(new java.awt.Color(51, 102, 255));
        Choose_routine_btn.setkStartColor(new java.awt.Color(255, 255, 255));
        Choose_routine_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Choose_routine_btnMousePressed(evt);
            }
        });
        Choose_routine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_routine_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Username_label)))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Choose_user_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                        .addComponent(Search_Type_label)
                                        .addGap(30, 30, 30)
                                        .addComponent(Choose_diet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Choose_routine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(Username_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Choose_user_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Search_Type_label)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Choose_diet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Choose_routine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DiscoverLayout = new javax.swing.GroupLayout(Discover);
        Discover.setLayout(DiscoverLayout);
        DiscoverLayout.setHorizontalGroup(
            DiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        DiscoverLayout.setVerticalGroup(
            DiscoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Discover, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        side_pane.setBackground(new java.awt.Color(0, 0, 0));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_btn.setBackground(new java.awt.Color(0, 0, 0));
        Home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Home_btnMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        javax.swing.GroupLayout Home_btnLayout = new javax.swing.GroupLayout(Home_btn);
        Home_btn.setLayout(Home_btnLayout);
        Home_btnLayout.setHorizontalGroup(
            Home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_btnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        Home_btnLayout.setVerticalGroup(
            Home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_btnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Home_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        Ranking_btn.setBackground(new java.awt.Color(23, 35, 51));
        Ranking_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ranking_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ranking_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Ranking_btnMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ranking");

        javax.swing.GroupLayout Ranking_btnLayout = new javax.swing.GroupLayout(Ranking_btn);
        Ranking_btn.setLayout(Ranking_btnLayout);
        Ranking_btnLayout.setHorizontalGroup(
            Ranking_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking_btnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        Ranking_btnLayout.setVerticalGroup(
            Ranking_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ranking_btnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Ranking_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Ranking_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, -1));

        Discover_btn.setBackground(new java.awt.Color(0, 0, 0));
        Discover_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Discover_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Discover_btnMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Discover");

        javax.swing.GroupLayout Discover_btnLayout = new javax.swing.GroupLayout(Discover_btn);
        Discover_btn.setLayout(Discover_btnLayout);
        Discover_btnLayout.setHorizontalGroup(
            Discover_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Discover_btnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        Discover_btnLayout.setVerticalGroup(
            Discover_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Discover_btnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Discover_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Discover_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        Create_btn.setBackground(new java.awt.Color(23, 35, 51));
        Create_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Create_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Create_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Create_btnMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Create");

        javax.swing.GroupLayout Create_btnLayout = new javax.swing.GroupLayout(Create_btn);
        Create_btn.setLayout(Create_btnLayout);
        Create_btnLayout.setHorizontalGroup(
            Create_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        Create_btnLayout.setVerticalGroup(
            Create_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Create_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        username_btn.setBorder(null);
        username_btn.setFont(new java.awt.Font("Yu Gothic Light", 0, 15)); // NOI18N
        username_btn.setkEndColor(new java.awt.Color(0, 0, 0));
        username_btn.setkFillButton(false);
        username_btn.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        username_btn.setkHoverForeGround(new java.awt.Color(51, 153, 255));
        username_btn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        username_btn.setkIndicatorThickness(1);
        username_btn.setkPressedColor(new java.awt.Color(0, 0, 0));
        username_btn.setkSelectedColor(new java.awt.Color(0, 0, 0));
        username_btn.setkStartColor(new java.awt.Color(0, 0, 0));
        username_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_btnActionPerformed(evt);
            }
        });
        side_pane.add(username_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 30));
        username_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                username_btnMousePressed(evt);
            }
        });

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        top_panel.setBackground(new java.awt.Color(71, 120, 197));
        top_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                top_panelMouseDragged(evt);
            }
        });
        top_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                top_panelMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Share my gym");

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360)
                .addComponent(btn_exit)
                .addGap(27, 27, 27))
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        kGradientPanel3.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("UPLOAD PUBLICATION");

        jLabel6.setText("Publication Type");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rutina", "Dieta" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel12.setText("Comment:");

        pie_foto.setColumns(20);
        pie_foto.setRows(5);
        jScrollPane1.setViewportView(pie_foto);

        Subir.setText("Upload");
        Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Subir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel12))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(Subir)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("TOP 10 RANKING");

        ranking.setModel(new javax.swing.table.DefaultTableModel(
            ranking_matriz,
            new String [] {
                "USUARIO","PUNTOS"
            }
        ));
        jScrollPane4.setViewportView(ranking);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout RankingLayout = new javax.swing.GroupLayout(Ranking);
        Ranking.setLayout(RankingLayout);
        RankingLayout.setHorizontalGroup(
            RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        RankingLayout.setVerticalGroup(
            RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        User_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        User_label.setText("User:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Surname:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("MODIFY YOUR PERSONAL DATA:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Name:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Surname:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Biography:");

        biografia.setText("jLabel19");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Biography:");

        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        modify_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_nameActionPerformed(evt);
            }
        });

        modify_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_surnameActionPerformed(evt);
            }
        });

        modify_bio.setColumns(20);
        modify_bio.setRows(5);
        jScrollPane5.setViewportView(modify_bio);

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userLayout.createSequentialGroup()
                                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modify_name, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(modify_surname))
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(50, 50, 50)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addComponent(User_label)
                        .addGap(18, 18, 18)
                        .addComponent(user_user, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(590, 590, 590))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addComponent(Submit)
                        .addGap(125, 125, 125))))
            .addGroup(userLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_user, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(surname_user, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(biografia, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                    .addContainerGap(581, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(284, 284, 284)))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(surname_user, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(biografia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(jLabel15)
                .addGap(37, 37, 37)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userLayout.createSequentialGroup()
                                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(modify_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(modify_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                            .addGroup(userLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(Submit)
                        .addGap(51, 51, 51))
                    .addGroup(userLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userLayout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(jLabel19)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );

        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 950, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_btnMousePressed
        // TODO add your handling code here:
        setColor(Home_btn); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Discover_btn,Create_btn}, new JPanel[]{ind_2,ind_3, ind_4});
         home.setVisible(true);
         Create.setVisible(false);
         Discover.setVisible(false);
        Ranking.setVisible(false);
        user.setVisible(false);
        
       
    }//GEN-LAST:event_Home_btnMousePressed

    private void Discover_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Discover_btnMousePressed
        // TODO add your handling code here:
         setColor(Discover_btn); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Home_btn,Create_btn}, new JPanel[]{ind_2,ind_1, ind_4});
         home.setVisible(false);
         Create.setVisible(false);
         Discover.setVisible(true);
        Ranking.setVisible(false);
        user.setVisible(false);
    }//GEN-LAST:event_Discover_btnMousePressed

    private void Create_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Create_btnMousePressed
        // TODO add your handling code here:
          setColor(Create_btn); 
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{Ranking_btn,Discover_btn,Home_btn}, new JPanel[]{ind_2,ind_3, ind_1});
         home.setVisible(false);
         Create.setVisible(true);
         Discover.setVisible(false);
        Ranking.setVisible(false);
        user.setVisible(false);
        
    }//GEN-LAST:event_Create_btnMousePressed

    private void Ranking_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ranking_btnMouseReleased
        // TODO add your handling code here:
          setColor(Ranking_btn); 
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{Home_btn,Discover_btn,Create_btn}, new JPanel[]{ind_1,ind_3, ind_4});
         home.setVisible(false);
         Create.setVisible(false);
         Discover.setVisible(false);
        Ranking.setVisible(true);
        user.setVisible(false);
    }//GEN-LAST:event_Ranking_btnMouseReleased

    int xx,xy;
    private void top_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_panelMousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_top_panelMousePressed

    private void top_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_panelMouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_top_panelMouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void username_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_username_btnActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void timelineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timelineMouseClicked
        // TODO add your handling code here:
        
        int column = timeline.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/timeline.getRowHeight();
        
        if(row < timeline.getRowCount() && row >= 0 && column < timeline.getColumnCount() && column >= 0){
            Object value = timeline.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                String comment="";
                int cont=0;
                while(cont<imagenes_timeline.size()){
                    if(imagenes_timeline.get(cont).getId().equals(boton.getName())){
                        comment=imagenes_timeline.get(cont).getDescripcion();
                    }
                    cont++;
                }
                
                JSONObject obj = new JSONObject();
                obj.put("publicacion", boton.getName());
                String result = ServerService.sendPost("verlikes.php", obj);
             
        
                likes_comments_gui gui= new likes_comments_gui(comment,usuarioObj,boton.getName(),result);
                gui.setVisible(true);
                gui.setDefaultCloseOperation(0);
            
            if(value instanceof JCheckBox){
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox)value;
                if(ch.isSelected()==true){
                    ch.setSelected(false);
                }
                if(ch.isSelected()==false){
                    ch.setSelected(true);
                }
                
            }
        }   
        }// TODO add your handling code here:
    }//GEN-LAST:event_timelineMouseClicked

    private void busqueda_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busqueda_tableMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        
        int column = busqueda_table.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/busqueda_table.getRowHeight();
        
        if(row < busqueda_table.getRowCount() && row >= 0 && column < busqueda_table.getColumnCount() && column >= 0){
            Object value = busqueda_table.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                 String comment="";
                 
                int cont=0;
                while(cont<imagenes_busqueda.size()){
                    if(imagenes_busqueda.get(cont).getId().equals(boton.getName())){
                        comment=imagenes_busqueda.get(cont).getDescripcion();
                    }
                    cont++;
                }
                
                JSONObject obj = new JSONObject();
                obj.put("publicacion", boton.getName());
                String result = ServerService.sendPost("verlikes.php", obj);   
                
                     likes_comments_gui gui= new likes_comments_gui(comment,usuarioObj,comment,result);
                       gui.setVisible(true);
                        gui.setDefaultCloseOperation(0);
            }
            if(value instanceof JCheckBox){
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox)value;
                if(ch.isSelected()==true){
                    ch.setSelected(false);
                }
                if(ch.isSelected()==false){
                    ch.setSelected(true);
                }
                
            }
        }        // TODO 
        
    }//GEN-LAST:event_busqueda_tableMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMousePressed

    private void Choose_user_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choose_user_btnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choose_user_btnMousePressed

    private void Choose_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_user_btnActionPerformed
        // TODO add your handling code here:
        username.setEnabled(true);
        Search.setEnabled(true);
       
       
        eleccion=1;
    }//GEN-LAST:event_Choose_user_btnActionPerformed

    private void Choose_diet_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choose_diet_btnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choose_diet_btnMousePressed

    private void Choose_diet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_diet_btnActionPerformed
        // TODO add your handling code here:
         username.setEnabled(false);
         Search.setEnabled(false);
      
        eleccion=2;
         Tabla v = new Tabla();
        JSONObject obj = new JSONObject();
        obj.put("tipo", "1");
               
        String result = ServerService.sendPost("buscarDieta_Rutina.php", obj);
        if(!result.equals("ZERO_RESULTS")){
            JSONParser parser = new JSONParser();
            try {  
                JSONArray jArray = (JSONArray) parser.parse(result);
            
                imagenes_busqueda=v.ver_tabla(busqueda_table,"Discover",jArray);
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR. THERE ARE NOT PUBLICATIONS", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Choose_diet_btnActionPerformed

    private void Choose_routine_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Choose_routine_btnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choose_routine_btnMousePressed

    private void Choose_routine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_routine_btnActionPerformed
        // TODO add your handling code here:
        username.setEnabled(false);
        Search.setEnabled(false);
        
        eleccion=3;
         Tabla v = new Tabla();
         JSONObject obj = new JSONObject();
        obj.put("tipo", "0");
               
        String result = ServerService.sendPost("buscarDieta_Rutina.php", obj);
        if(!result.equals("ZERO_RESULTS")){
            JSONParser parser = new JSONParser();
            try {  
                JSONArray jArray = (JSONArray) parser.parse(result);
            
                imagenes_busqueda=v.ver_tabla(busqueda_table,"Discover",jArray);
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR. THERE ARE NOT PUBLICATIONS", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Choose_routine_btnActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        //Controllers.Discover
        
    }//GEN-LAST:event_SearchActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirActionPerformed
        // TODO add your handling code here:
        Upload subir=new Upload(pie_foto.getText(),tipo.getSelectedIndex(), usuarioObj.getUser(),usuarioObj.getPassword());
        
        subir.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_SubirActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        JSONObject obj = new JSONObject();
        obj.put("username", username.getText());
       
        v = new Tabla();       
        String result = ServerService.sendPost("buscar.php", obj);
        if(!result.equals("ZERO_RESULTS")){
            JSONParser parser = new JSONParser();
            try {  
                JSONArray jArray = (JSONArray) parser.parse(result);
            
                imagenes_busqueda=v.ver_tabla(busqueda_table,"Discover",jArray);
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR. THERE ARE NOT PUBLICATIONS", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
             
    }//GEN-LAST:event_SearchMouseClicked

    private void modify_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modify_surnameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
        
         JSONObject obj = new JSONObject();
        obj.put("update", "1");
        obj.put("username", usuarioObj.getUser());
        obj.put("name", modify_name.getText());
        obj.put("surnames", modify_surname.getText());
        obj.put("bio", modify_bio.getText());
       metodos m =new metodos();
       m.modificar_datos(obj);
        
        
    }//GEN-LAST:event_SubmitMouseClicked

    private void modify_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modify_nameActionPerformed
    private void lblMouseClicked(java.awt.event.MouseEvent evt){
        System.out.println("holaamigos");
    }
    private void bnt1MousePressed(java.awt.event.MouseEvent evt) throws IOException{                                         
        // TODO add your handling code here:
        Home h =new Home();
        h.setVisible(true);
        dispose();
        
        
    }
    private void username_btnMousePressed(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        home.setVisible(false);
        Create.setVisible(false);
        Discover.setVisible(false);
        Ranking.setVisible(false);
        user.setVisible(true);
        
        JSONObject obj = new JSONObject();
        obj.put("update", "0");
        obj.put("username", usuarioObj.getUser());
       
        String result = ServerService.sendPost("profile.php", obj);
         JSONParser parser = new JSONParser();
            
         try {  
                JSONArray jArray = (JSONArray) parser.parse(result);
             name_user.setText((String) jArray.get(0));
             user_user.setText(usuarioObj.getUser());
             surname_user.setText((String) jArray.get(1));
             biografia.setText((String) jArray.get(2));
            } catch (ParseException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
       
       
        
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(0,0,0));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton Choose_diet_btn;
    private keeptoo.KButton Choose_routine_btn;
    private keeptoo.KButton Choose_user_btn;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Create_btn;
    private javax.swing.JPanel Discover;
    private javax.swing.JPanel Discover_btn;
    private javax.swing.JPanel Home_btn;
    private javax.swing.JPanel Ranking;
    private javax.swing.JPanel Ranking_btn;
    private keeptoo.KButton Search;
    private javax.swing.JLabel Search_Type_label;
    private javax.swing.JToggleButton Subir;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel User_label;
    private javax.swing.JLabel Username_label;
    private javax.swing.JLabel biografia;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JTable busqueda_table;
    private javax.swing.JPanel home;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JTextArea modify_bio;
    private javax.swing.JTextField modify_name;
    private javax.swing.JTextField modify_surname;
    private javax.swing.JLabel name_user;
    private javax.swing.JTextArea pie_foto;
    private javax.swing.JTable ranking;
    private javax.swing.JPanel side_pane;
    private javax.swing.JLabel surname_user;
    private javax.swing.JTable timeline;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JPanel top_panel;
    private javax.swing.JPanel user;
    private javax.swing.JLabel user_user;
    private javax.swing.JTextField username;
    private keeptoo.KButton username_btn;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel foto_c;
    private int eleccion;
    
}
